language: emacs-lisp
before_install:
  - curl -fsSkL https://gist.github.com/senny/8003271/raw > travis.sh && source ./travis.sh
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip
  - cask
env:
  - EVM_EMACS=emacs-24.1-travis
  - EVM_EMACS=emacs-24.2-travis
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
script:
  - emacs --version
  - make test
